spring.application.name=gestao-frota

# Mudar para porta 5432 para usar na flash (casa é 5433)
# Senha flash: guigil2225 | Senha casa: alaska
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao-frota
spring.datasource.username=postgres
spring.datasource.password=guigil2225

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect