POST http://localhost:8080/api/funcionarios
Content-Type: application/json

{
  "nome": "Guilherme Gil",
  "cpf": "123.456.789-04",
  "rg": "12.345.678-8",
  "setor": "TI",
  "permissao": "ADMIN",
  "ativo": true,
  "criadoEm": "2026-02-22T18:15:00"
}